# Generated by Django 4.2.6 on 2024-12-02 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_course_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
            ],
        ),
    ]
